# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aT90hm_v9H5aOSllexu-hBHb9CGXShf
"""

import pandas as pd
import io

# Cargar el archivo CSV
# Nota: Asegúrate de haber subido el archivo con este nombre exacto a la carpeta de la izquierda en Colab
file_name = 'Narración Gráfica Santiago en 100 palabras   - V Edición.csv'

try:
    # Intentamos cargar con UTF-8
    df = pd.read_csv(file_name, encoding='utf-8')
    print("Archivo cargado exitosamente con codificación UTF-8.\n")
except:
    # Si falla, intentamos con Latin-1 (común en archivos CSV de Excel en español)
    df = pd.read_csv(file_name, encoding='latin-1')
    print("Archivo cargado exitosamente con codificación Latin-1.\n")

# 1. Visualizar las primeras 10 filas
print("Primeras filas de la base de datos:")
display(df.head(10))

# 2. Resumen de la base de datos para el historial de decisiones
print("\nInformación técnica de las variables:")
df.info()

# 3. Ejemplo de pregunta para el reportaje: ¿Cuántos autores hay por género?
print("\nDistribución por Género:")
print(df['Género'].value_counts())